title: Joseph V. Casillas
name: Joseph V. Casillas
email: jvcasill@email.arizona.edu
github: jvcasill
twitter: jvcasill
pygments: true
timezone: TIMEZONE
  
# Settings for analytics
analytics :
  provider : google
  google : 
      tracking_id : UA-27236322-1