title: Academic website
name: Joseph V. Casillas
author: Joseph V. Casillas
email: jvcasill@email.arizona.edu
github: jvcasill
twitter: jvcasill
pygments: true
source: _source
timezone: TIMEZONE
  
# Settings for analytics
analytics :
  provider : google
  google : 
      tracking_id : UA-27236322-1