name: Joseph V. Casillas
pygments: true
source: _source
timezone: TIMEZONE

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
      tracking_id : UA-27236322-1