title: Joseph V. Casillas
name: Joseph V. Casillas
email: jvcasill@email.arizona.edu
github: jvcasill
twitter: jvcasill
pygments: true
timezone: TIMEZONE
markdown: kramdown

# HIGHLIGHTER SETTINGS
highlighter: prettify
hitheme: twitter-bootstrap
prettify:
  linenums: true

# WIDGETS
widgets: [disqus, mathjax]
disqus:
  shortname: slidify

# Settings for analytics
analytics :
  provider : google
  google : 
      tracking_id : UA-27236322-1