title: Joseph V. Casillas
tagline: ""
theme: "01"
reverse: False
description: >


url: "http://www.jvcasillas.com"
author:
  name: "Joseph V. Casillas"
  github: "jvcasill"
  twitter: "jvcasill"


sidebar:
  - {item: bio, href: '/bio', icon: 'puzzle-piece'}
  - {item: teaching, href: '/teaching', icon: 'pencil-square'}
  - {item: research, href: '/research', icon: 'cogs'}
  - {item: cv, href: '/cv', icon: 'puzzle-piece'}
  - {item: code, href: '/code', icon: 'code'}
  - {item: blog, href: '/blog', icon: 'archive'}


projects:
  - {title: "lingStuff", 
     url: "http://www.jvcasillas.com/lingStuff/index.html",
     thumbnail: 'lingstuff.png'
    }
  - {title: "R-Snippets", 
     url: "http://www.jvcasillas.com/code/projects/R-snippets",
     thumbnail: 'lm.png'
    }
  - {title: "lingreference.org", 
     url: "http://www.jvcasillas.com/code/projects/lingreference",
     thumbnail: 'lingref.png'
    }
  - {title: "LaTeX-IPA", 
     url: "http://www.jvcasillas.com/code/projects/latex-ipa",
     thumbnail: 'vowel_space.png'
    }




# Settings for analytics
analytics :
  provider : google
  google : 
      tracking_id : UA-27236322-1
