title: jvcasillas
tagline: testing
owner: Joseph V. Casillas
author:
  email: jvcasill@email.arizona.edu
  github: jvcasill
  firstname: Joseph
  lastname: Casillas

social:
  github: jvcasill
  twitter: jvcasill

# Choose url: / for local development
url: http://jvcasill.github.com/jvcasill/
rawurl: https://raw.github.com/jvcasill/jvcasill/gh-pages/
# url: /
URL: http://github.com/jvcasill/jvcasill
navigation: 
  - {item: Home, href: index.html}
