mode     : selfcontained
framework: purus
github:
  user: jvcasill
  repo: jvcasill.github.io

# HIGHLIGHTER SETTINGS
highlighter: prettify
hitheme: twitter-bootstrap
prettify:
  linenums: true

url:
  lib: ../assests
  assets: ../assets

# WIDGETS
widgets: [disqus, mathjax]
disqus:
  shortname: slidify



